// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACY-i1apXLGzlPjClm0cEBydSDQAthbA',
    appId: '1:747231265944:web:be2de26d90456fdf45bced',
    messagingSenderId: '747231265944',
    projectId: 'controle-de-abastecimento2',
    authDomain: 'controle-de-abastecimento2.firebaseapp.com',
    storageBucket: 'controle-de-abastecimento2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArHBP5b8RUlI7dy8502DjTdQgftUxx7wI',
    appId: '1:747231265944:android:cb7bca175958977645bced',
    messagingSenderId: '747231265944',
    projectId: 'controle-de-abastecimento2',
    storageBucket: 'controle-de-abastecimento2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx5mOh1pgsT3Qr5DJyYBJwEJun4xOVCh4',
    appId: '1:747231265944:ios:f1a93fbdb89e543d45bced',
    messagingSenderId: '747231265944',
    projectId: 'controle-de-abastecimento2',
    storageBucket: 'controle-de-abastecimento2.firebasestorage.app',
    iosBundleId: 'com.example.abastecimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx5mOh1pgsT3Qr5DJyYBJwEJun4xOVCh4',
    appId: '1:747231265944:ios:f1a93fbdb89e543d45bced',
    messagingSenderId: '747231265944',
    projectId: 'controle-de-abastecimento2',
    storageBucket: 'controle-de-abastecimento2.firebasestorage.app',
    iosBundleId: 'com.example.abastecimento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCACY-i1apXLGzlPjClm0cEBydSDQAthbA',
    appId: '1:747231265944:web:c7641bef051046af45bced',
    messagingSenderId: '747231265944',
    projectId: 'controle-de-abastecimento2',
    authDomain: 'controle-de-abastecimento2.firebaseapp.com',
    storageBucket: 'controle-de-abastecimento2.firebasestorage.app',
  );
}
